// CoinGecko identifies each coin by a slug ("id"), not its ticker symbol.
// This is a curated list of widely-traded coins; the tool also lets someone
// type a custom CoinGecko id for anything not on this shortlist.
export const CRYPTO_COINS = [
  { id: 'bitcoin', symbol: 'BTC', name: 'Bitcoin' },
  { id: 'ethereum', symbol: 'ETH', name: 'Ethereum' },
  { id: 'tether', symbol: 'USDT', name: 'Tether' },
  { id: 'binancecoin', symbol: 'BNB', name: 'BNB' },
  { id: 'solana', symbol: 'SOL', name: 'Solana' },
  { id: 'ripple', symbol: 'XRP', name: 'XRP' },
  { id: 'usd-coin', symbol: 'USDC', name: 'USD Coin' },
  { id: 'cardano', symbol: 'ADA', name: 'Cardano' },
  { id: 'dogecoin', symbol: 'DOGE', name: 'Dogecoin' },
  { id: 'tron', symbol: 'TRX', name: 'TRON' },
  { id: 'avalanche-2', symbol: 'AVAX', name: 'Avalanche' },
  { id: 'chainlink', symbol: 'LINK', name: 'Chainlink' },
  { id: 'polkadot', symbol: 'DOT', name: 'Polkadot' },
  { id: 'matic-network', symbol: 'MATIC', name: 'Polygon' },
  { id: 'litecoin', symbol: 'LTC', name: 'Litecoin' },
  { id: 'shiba-inu', symbol: 'SHIB', name: 'Shiba Inu' },
  { id: 'uniswap', symbol: 'UNI', name: 'Uniswap' },
  { id: 'cosmos', symbol: 'ATOM', name: 'Cosmos' },
  { id: 'stellar', symbol: 'XLM', name: 'Stellar' },
  { id: 'monero', symbol: 'XMR', name: 'Monero' },
  { id: 'near', symbol: 'NEAR', name: 'NEAR Protocol' },
  { id: 'internet-computer', symbol: 'ICP', name: 'Internet Computer' },
  { id: 'aptos', symbol: 'APT', name: 'Aptos' },
  { id: 'filecoin', symbol: 'FIL', name: 'Filecoin' },
  { id: 'vechain', symbol: 'VET', name: 'VeChain' },
  { id: 'algorand', symbol: 'ALGO', name: 'Algorand' },
  { id: 'hedera-hashgraph', symbol: 'HBAR', name: 'Hedera' },
  { id: 'the-graph', symbol: 'GRT', name: 'The Graph' },
  { id: 'aave', symbol: 'AAVE', name: 'Aave' },
  { id: 'maker', symbol: 'MKR', name: 'Maker' },
  { id: 'sui', symbol: 'SUI', name: 'Sui' },
  { id: 'pepe', symbol: 'PEPE', name: 'Pepe' },
  { id: 'dogwifcoin', symbol: 'WIF', name: 'dogwifhat' },
  { id: 'bonk', symbol: 'BONK', name: 'Bonk' },
  { id: 'floki', symbol: 'FLOKI', name: 'FLOKI' },
  { id: 'meme', symbol: 'MEME', name: 'Memecoin' },
  { id: 'popcat', symbol: 'POPCAT', name: 'Popcat' }
]
