// A much larger synonym table for the rule-based rephraser, aimed at the
// kind of formal/academic/business vocabulary that shows up in reports and
// essays (not just everyday words). Where a word commonly appears with
// -s/-ed/-ing endings, those forms are listed explicitly with matching
// inflected synonyms, since this is a simple word-swap tool, not a real
// grammar engine — guessing inflections algorithmically tends to produce
// worse results than just listing the common forms directly.
//
// This is still a rough, rule-based pass, not AI rewriting: it swaps
// individual words it recognizes and leaves everything else exactly as
// written. Words not in this list (names, jargon, acronyms) are untouched
// by design.
export const SYNONYMS = {
  // --- everyday basics (kept from the original set) ---
  good: ['solid', 'strong', 'decent', 'fine'],
  bad: ['poor', 'weak', 'subpar'],
  important: ['key', 'significant', 'essential', 'critical'],
  big: ['large', 'sizeable', 'substantial'],
  small: ['minor', 'compact', 'modest'],
  fast: ['quick', 'rapid', 'swift'],
  slow: ['gradual', 'unhurried'],
  happy: ['pleased', 'glad', 'content'],
  sad: ['unhappy', 'downcast'],
  help: ['assist', 'support', 'aid'],
  helps: ['assists', 'supports', 'aids'],
  helped: ['assisted', 'supported', 'aided'],
  helping: ['assisting', 'supporting', 'aiding'],
  use: ['utilize', 'apply', 'employ'],
  uses: ['utilizes', 'applies', 'employs'],
  used: ['utilized', 'applied', 'employed'],
  using: ['utilizing', 'applying', 'employing'],
  show: ['demonstrate', 'display', 'reveal'],
  shows: ['demonstrates', 'displays', 'reveals'],
  showed: ['demonstrated', 'displayed', 'revealed'],
  showing: ['demonstrating', 'displaying', 'revealing'],
  make: ['create', 'produce', 'build'],
  makes: ['creates', 'produces', 'builds'],
  made: ['created', 'produced', 'built'],
  making: ['creating', 'producing', 'building'],
  get: ['obtain', 'acquire', 'gain'],
  gets: ['obtains', 'acquires', 'gains'],
  got: ['obtained', 'acquired', 'gained'],
  getting: ['obtaining', 'acquiring', 'gaining'],
  start: ['begin', 'launch', 'initiate'],
  starts: ['begins', 'launches', 'initiates'],
  started: ['began', 'launched', 'initiated'],
  starting: ['beginning', 'launching', 'initiating'],
  end: ['finish', 'conclude', 'wrap up'],
  ends: ['finishes', 'concludes'],
  ended: ['finished', 'concluded'],
  because: ['since', 'as', 'given that'],
  but: ['however', 'yet', 'though'],
  also: ['additionally', 'as well', 'furthermore'],
  very: ['quite', 'extremely', 'remarkably'],
  many: ['numerous', 'a number of', 'plenty of'],
  problem: ['issue', 'challenge', 'difficulty'],
  problems: ['issues', 'challenges', 'difficulties'],
  idea: ['concept', 'notion', 'thought'],
  ideas: ['concepts', 'notions', 'thoughts'],
  change: ['shift', 'adjust', 'modify'],
  changes: ['shifts', 'adjusts', 'modifies'],
  changed: ['shifted', 'adjusted', 'modified'],
  changing: ['shifting', 'adjusting', 'modifying'],
  improve: ['enhance', 'refine', 'upgrade'],
  improves: ['enhances', 'refines', 'upgrades'],
  improved: ['enhanced', 'refined', 'upgraded'],
  improving: ['enhancing', 'refining', 'upgrading'],
  need: ['require', 'call for'],
  needs: ['requires', 'calls for'],
  needed: ['required'],
  think: ['believe', 'consider', 'reckon'],
  said: ['stated', 'mentioned', 'noted'],
  today: ['nowadays', 'currently'],
  easy: ['simple', 'straightforward'],
  hard: ['difficult', 'demanding', 'tough'],
  new: ['recent', 'fresh', 'modern'],
  old: ['previous', 'former', 'dated'],
  clear: ['evident', 'apparent', 'obvious'],
  keep: ['retain', 'maintain', 'preserve'],
  give: ['provide', 'offer', 'supply'],
  gives: ['provides', 'offers', 'supplies'],
  gave: ['provided', 'offered', 'supplied'],
  giving: ['providing', 'offering', 'supplying'],
  find: ['locate', 'identify', 'discover'],
  finds: ['locates', 'identifies', 'discovers'],
  found: ['located', 'identified', 'discovered'],
  finding: ['locating', 'identifying', 'discovering'],
  understand: ['grasp', 'comprehend'],
  understands: ['grasps', 'comprehends'],
  understanding: ['grasping', 'comprehending'],
  create: ['build', 'develop', 'craft'],
  creates: ['builds', 'develops', 'crafts'],
  created: ['built', 'developed', 'crafted'],
  creating: ['building', 'developing', 'crafting'],
  different: ['distinct', 'varied', 'diverse'],
  effective: ['efficient', 'productive'],
  quick: ['fast', 'rapid', 'speedy'],

  // --- formal / report / academic vocabulary ---
  background: ['context', 'backdrop'],
  information: ['data', 'details'],
  combine: ['merge', 'blend', 'pair'],
  combines: ['merges', 'blends', 'pairs'],
  combined: ['merged', 'blended', 'paired'],
  combining: ['merging', 'blending', 'pairing'],
  leverage: ['make use of', 'draw on', 'harness'],
  leverages: ['makes use of', 'draws on', 'harnesses'],
  leveraged: ['made use of', 'drew on', 'harnessed'],
  leveraging: ['making use of', 'drawing on', 'harnessing'],
  enhance: ['improve', 'strengthen', 'boost'],
  enhances: ['improves', 'strengthens', 'boosts'],
  enhanced: ['improved', 'strengthened', 'boosted'],
  enhancing: ['improving', 'strengthening', 'boosting'],
  multiple: ['several', 'numerous', 'various'],
  interaction: ['exchange', 'engagement'],
  interactions: ['exchanges', 'engagements'],
  interact: ['engage', 'communicate'],
  interacts: ['engages', 'communicates'],
  interacted: ['engaged', 'communicated'],
  interacting: ['engaging', 'communicating'],
  natural: ['intuitive', 'organic'],
  seamless: ['smooth', 'fluid', 'frictionless'],
  intuitive: ['natural', 'instinctive'],
  experience: ['encounter', 'engagement'],
  experiences: ['encounters', 'engagements'],
  technology: ['tech', 'technological tools'],
  mimic: ['resemble', 'echo', 'replicate'],
  mimics: ['resembles', 'echoes', 'replicates'],
  mimicked: ['resembled', 'echoed', 'replicated'],
  mimicking: ['resembling', 'echoing', 'replicating'],
  allow: ['let', 'enable', 'permit'],
  allows: ['lets', 'enables', 'permits'],
  allowed: ['let', 'enabled', 'permitted'],
  allowing: ['letting', 'enabling', 'permitting'],
  context: ['background', 'setting'],
  relevance: ['significance', 'importance'],
  usability: ['ease of use', 'user-friendliness'],
  significant: ['notable', 'considerable', 'substantial'],
  significantly: ['notably', 'considerably', 'substantially'],
  various: ['diverse', 'assorted', 'numerous'],
  utilize: ['use', 'employ', 'apply'],
  utilizes: ['uses', 'employs', 'applies'],
  utilized: ['used', 'employed', 'applied'],
  utilizing: ['using', 'employing', 'applying'],
  demonstrate: ['show', 'illustrate', 'reveal'],
  demonstrates: ['shows', 'illustrates', 'reveals'],
  demonstrated: ['showed', 'illustrated', 'revealed'],
  demonstrating: ['showing', 'illustrating', 'revealing'],
  indicate: ['suggest', 'signal', 'point to'],
  indicates: ['suggests', 'signals', 'points to'],
  indicated: ['suggested', 'signaled', 'pointed to'],
  facilitate: ['ease', 'enable', 'streamline'],
  facilitates: ['eases', 'enables', 'streamlines'],
  facilitated: ['eased', 'enabled', 'streamlined'],
  facilitating: ['easing', 'enabling', 'streamlining'],
  establish: ['set up', 'form', 'set out'],
  establishes: ['sets up', 'forms', 'sets out'],
  established: ['set up', 'formed'],
  establishing: ['setting up', 'forming'],
  implement: ['carry out', 'put in place', 'execute'],
  implements: ['carries out', 'puts in place', 'executes'],
  implemented: ['carried out', 'put in place', 'executed'],
  implementing: ['carrying out', 'putting in place', 'executing'],
  maintain: ['sustain', 'preserve', 'uphold'],
  maintains: ['sustains', 'preserves', 'upholds'],
  maintained: ['sustained', 'preserved', 'upheld'],
  ensure: ['guarantee', 'make certain'],
  ensures: ['guarantees', 'makes certain'],
  ensured: ['guaranteed'],
  ensuring: ['guaranteeing', 'making certain'],
  require: ['need', 'call for', 'demand'],
  requires: ['needs', 'calls for', 'demands'],
  required: ['needed', 'called for', 'demanded'],
  requiring: ['needing', 'calling for', 'demanding'],
  provide: ['supply', 'offer', 'deliver'],
  provides: ['supplies', 'offers', 'delivers'],
  provided: ['supplied', 'offered', 'delivered'],
  providing: ['supplying', 'offering', 'delivering'],
  enable: ['allow', 'let', 'empower'],
  enables: ['allows', 'lets', 'empowers'],
  enabled: ['allowed', 'let', 'empowered'],
  enabling: ['allowing', 'letting', 'empowering'],
  achieve: ['attain', 'accomplish', 'reach'],
  achieves: ['attains', 'accomplishes', 'reaches'],
  achieved: ['attained', 'accomplished', 'reached'],
  achieving: ['attaining', 'accomplishing', 'reaching'],
  obtain: ['acquire', 'secure', 'gain'],
  obtains: ['acquires', 'secures', 'gains'],
  obtained: ['acquired', 'secured', 'gained'],
  generate: ['produce', 'create', 'yield'],
  generates: ['produces', 'creates', 'yields'],
  generated: ['produced', 'created', 'yielded'],
  generating: ['producing', 'creating', 'yielding'],
  reduce: ['lower', 'decrease', 'cut down'],
  reduces: ['lowers', 'decreases', 'cuts down'],
  reduced: ['lowered', 'decreased'],
  reducing: ['lowering', 'decreasing'],
  increase: ['raise', 'grow', 'expand'],
  increases: ['raises', 'grows', 'expands'],
  increased: ['raised', 'grew', 'expanded'],
  increasing: ['raising', 'growing', 'expanding'],
  decrease: ['reduce', 'decline', 'drop'],
  decreases: ['reduces', 'declines', 'drops'],
  decreased: ['reduced', 'declined', 'dropped'],
  numerous: ['many', 'several', 'countless'],
  substantial: ['considerable', 'sizeable', 'significant'],
  essential: ['vital', 'crucial', 'fundamental'],
  fundamental: ['basic', 'core', 'essential'],
  critical: ['crucial', 'vital', 'essential'],
  primary: ['main', 'principal', 'chief'],
  secondary: ['lesser', 'subordinate'],
  additional: ['further', 'extra', 'supplementary'],
  diverse: ['varied', 'assorted', 'wide-ranging'],
  complex: ['complicated', 'intricate'],
  simple: ['straightforward', 'basic', 'uncomplicated'],
  efficient: ['effective', 'streamlined'],
  innovative: ['inventive', 'novel', 'groundbreaking'],
  traditional: ['conventional', 'established', 'customary'],
  contemporary: ['modern', 'current', 'present-day'],
  potential: ['possible', 'prospective'],
  particular: ['specific', 'certain'],
  specific: ['particular', 'precise'],
  general: ['broad', 'overall'],
  current: ['present', 'existing'],
  future: ['upcoming', 'forthcoming'],
  previous: ['prior', 'earlier'],
  recent: ['latest', 'newest'],
  ongoing: ['continuing', 'in progress'],
  continuous: ['constant', 'uninterrupted'],
  initial: ['first', 'starting'],
  final: ['last', 'concluding'],
  ultimate: ['final', 'eventual'],
  comprehensive: ['thorough', 'extensive', 'complete'],
  extensive: ['broad', 'wide-ranging', 'comprehensive'],
  detailed: ['thorough', 'in-depth'],
  brief: ['short', 'concise'],
  concise: ['brief', 'succinct'],
  thorough: ['comprehensive', 'detailed', 'exhaustive'],
  apparent: ['evident', 'clear', 'obvious'],
  evident: ['apparent', 'clear', 'obvious'],
  obvious: ['clear', 'apparent', 'evident'],
  crucial: ['critical', 'vital', 'essential'],
  vital: ['essential', 'crucial', 'critical'],
  necessary: ['required', 'essential', 'needed'],
  sufficient: ['adequate', 'enough'],
  adequate: ['sufficient', 'satisfactory'],
  appropriate: ['suitable', 'fitting', 'apt'],
  suitable: ['appropriate', 'fitting'],
  relevant: ['pertinent', 'applicable'],
  applicable: ['relevant', 'pertinent'],
  feasible: ['viable', 'workable', 'practical'],
  viable: ['feasible', 'workable'],
  sustainable: ['lasting', 'long-term'],
  reliable: ['dependable', 'trustworthy', 'consistent'],
  consistent: ['steady', 'uniform', 'reliable'],
  accurate: ['precise', 'exact', 'correct'],
  precise: ['exact', 'accurate', 'specific'],
  flexible: ['adaptable', 'versatile'],
  robust: ['sturdy', 'resilient', 'strong'],
  scalable: ['expandable', 'adaptable'],
  integrated: ['combined', 'unified', 'consolidated'],
  advanced: ['sophisticated', 'cutting-edge'],
  modern: ['contemporary', 'current', 'up-to-date'],
  overview: ['summary', 'synopsis'],
  aspect: ['element', 'facet', 'feature'],
  aspects: ['elements', 'facets', 'features'],
  factor: ['element', 'consideration'],
  factors: ['elements', 'considerations'],
  concept: ['idea', 'notion'],
  concepts: ['ideas', 'notions'],
  method: ['approach', 'technique', 'process'],
  methods: ['approaches', 'techniques', 'processes'],
  approach: ['method', 'technique', 'strategy'],
  approaches: ['methods', 'techniques', 'strategies'],
  strategy: ['approach', 'plan', 'tactic'],
  strategies: ['approaches', 'plans', 'tactics'],
  process: ['procedure', 'method'],
  processes: ['procedures', 'methods'],
  purpose: ['aim', 'objective', 'goal'],
  goal: ['aim', 'objective', 'target'],
  goals: ['aims', 'objectives', 'targets'],
  objective: ['aim', 'goal', 'target'],
  objectives: ['aims', 'goals', 'targets'],
  outcome: ['result', 'consequence'],
  outcomes: ['results', 'consequences'],
  result: ['outcome', 'consequence'],
  results: ['outcomes', 'consequences'],
  benefit: ['advantage', 'upside'],
  benefits: ['advantages', 'upsides'],
  advantage: ['benefit', 'upside'],
  advantages: ['benefits', 'upsides'],
  challenge: ['difficulty', 'obstacle'],
  challenges: ['difficulties', 'obstacles'],
  solution: ['answer', 'fix', 'remedy'],
  solutions: ['answers', 'fixes', 'remedies'],
  issue: ['problem', 'matter'],
  issues: ['problems', 'matters'],
  impact: ['effect', 'influence'],
  impacts: ['effects', 'influences'],
  influence: ['impact', 'effect', 'sway'],
  perspective: ['viewpoint', 'standpoint'],
  perspectives: ['viewpoints', 'standpoints'],
  consider: ['examine', 'weigh', 'assess'],
  considers: ['examines', 'weighs', 'assesses'],
  considered: ['examined', 'weighed', 'assessed'],
  considering: ['examining', 'weighing', 'assessing'],
  analyze: ['examine', 'assess', 'evaluate'],
  analyzes: ['examines', 'assesses', 'evaluates'],
  analyzed: ['examined', 'assessed', 'evaluated'],
  analyzing: ['examining', 'assessing', 'evaluating'],
  evaluate: ['assess', 'examine', 'appraise'],
  evaluates: ['assesses', 'examines', 'appraises'],
  evaluated: ['assessed', 'examined', 'appraised'],
  assess: ['evaluate', 'examine', 'appraise'],
  assesses: ['evaluates', 'examines', 'appraises'],
  assessed: ['evaluated', 'examined', 'appraised'],
  examine: ['assess', 'evaluate', 'inspect'],
  examines: ['assesses', 'evaluates', 'inspects'],
  examined: ['assessed', 'evaluated', 'inspected'],
  determine: ['establish', 'figure out', 'identify'],
  determines: ['establishes', 'figures out', 'identifies'],
  determined: ['established', 'figured out', 'identified'],
  identify: ['pinpoint', 'recognize', 'determine'],
  identifies: ['pinpoints', 'recognizes', 'determines'],
  identified: ['pinpointed', 'recognized', 'determined'],
  recognize: ['identify', 'acknowledge'],
  recognizes: ['identifies', 'acknowledges'],
  recognized: ['identified', 'acknowledged'],
  address: ['tackle', 'deal with', 'handle'],
  addresses: ['tackles', 'deals with', 'handles'],
  addressed: ['tackled', 'dealt with', 'handled'],
  addressing: ['tackling', 'dealing with', 'handling'],
  support: ['back', 'reinforce', 'sustain'],
  supports: ['backs', 'reinforces', 'sustains'],
  supported: ['backed', 'reinforced', 'sustained'],
  supporting: ['backing', 'reinforcing', 'sustaining'],
  include: ['incorporate', 'contain', 'encompass'],
  includes: ['incorporates', 'contains', 'encompasses'],
  included: ['incorporated', 'contained', 'encompassed'],
  including: ['incorporating', 'containing', 'encompassing'],
  focus: ['emphasis', 'concentration'],
  focuses: ['concentrates', 'centers'],
  focused: ['concentrated', 'centered'],
  highlight: ['emphasize', 'underscore', 'spotlight'],
  highlights: ['emphasizes', 'underscores', 'spotlights'],
  highlighted: ['emphasized', 'underscored', 'spotlighted'],
  emphasize: ['stress', 'underscore', 'highlight'],
  emphasizes: ['stresses', 'underscores', 'highlights'],
  emphasized: ['stressed', 'underscored', 'highlighted'],
  regarding: ['concerning', 'about', 'with respect to'],
  overall: ['on the whole', 'broadly'],
  therefore: ['thus', 'consequently', 'hence'],
  thus: ['therefore', 'hence', 'consequently'],
  moreover: ['furthermore', 'additionally'],
  furthermore: ['moreover', 'additionally'],
  however: ['nevertheless', 'yet', 'still'],
  although: ['though', 'even though'],
  despite: ['in spite of', 'notwithstanding'],
  through: ['via', 'by means of'],
  within: ['inside', 'in']
}

function pick(list, seed) {
  return list[seed % list.length]
}

export function rephrase(text) {
  let seed = 0
  return text.replace(/[A-Za-z']+/g, (word) => {
    const lower = word.toLowerCase()
    const options = SYNONYMS[lower]
    if (!options) return word
    seed += 1
    const replacement = pick(options, seed)
    // preserve capitalization of the original word
    if (word === word.toUpperCase() && word.length > 1) {
      return replacement.toUpperCase()
    }
    if (word[0] === word[0].toUpperCase()) {
      return replacement.charAt(0).toUpperCase() + replacement.slice(1)
    }
    return replacement
  })
}
